Added ExceedanceOutOfRange handling
ucgmsim/gmhazard pull request #84
Opened 2022-06-28 21:24 UTC by claudio525

2022-06-28 21:41 UTC, jasonmotha approved these changes

2022-06-28 21:42 UTC, SnowNooDLe requested changes

2022-06-28 21:42 UTC, SnowNooDLe commented on tools/project_gen/project_gen/gms.py
> +                       and cur_im.component is gc.im.IMComponent.RotD50
Accidentally added extra indentation? haha

2022-06-28 22:02 UTC, SnowNooDLe submitted a review, later dismissed

2022-06-28 22:25 UTC, joelridden approved these changes

2022-06-29 00:41 UTC, jasonmotha approved these changes

2022-06-29 08:48 UTC, SnowNooDLe approved these changes

2022-06-29 20:32 UTC, merged